issues:
  exclude-rules:
    - path: buildkite/agent.go
      linters:
        # type assertion does not need checking as this will run in linux only (via Docker)
        - forcetypeassert

linters:
  enable-all: true
  disable:
  - gochecknoglobals
  - wrapcheck
  - varnamelen
  - tagliatelle
  - testpackage
  - paralleltest
  - err113
  - dupl
  - forbidigo
  - funlen
  - unparam
  - wsl
  - errname
  - exhaustruct
  - nilnil
  - nlreturn
  - goconst
  - lll
  - asciicheck
  - gocognit
  - godot
  - godox
  - gofumpt
  - nestif
  - prealloc
  - revive
  - depguard

linters-settings:
  gosec:
    # all rules enabled
    # see also: https://securego.io/docs/rules/rule-intro.html
    config:
      global:
        # allow #nosec override comments
        nosec: enabled
        # disable potentially noisy stricter audit mode
        audit: disabled
      G101: # "Look for hard-coded credentials"
        mode: strict
  cyclop:
    max-complexity: 20
