name: ECS Task Runner
description: >
  A Golang-based plugin to dispatch ECS tasks.
author: https://github.com/cultureamp
requirements: []
configuration:
  properties:
    parameter-name:
      type: string
    command:
      type: string
    timeout:
      type: integer
  additionalProperties: false
  anyOf:
    - required:
        - parameter-name
